/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "secondary-fixed-dim": "#c5c7c8",
              "on-primary": "#ffffff",
              "primary-fixed-dim": "#c2c4e8",
              "surface-container-lowest": "#ffffff",
              "secondary": "#5c5f60",
              "on-tertiary-container": "#f1414d",
              "outline-variant": "#c7c5ce",
              "surface-variant": "#e1e3e4",
              "on-tertiary": "#ffffff",
              "on-tertiary-fixed": "#410007",
              "on-surface-variant": "#46464d",
              "on-secondary-fixed": "#191c1d",
              "tertiary-fixed-dim": "#ffb3b1",
              "on-error-container": "#93000a",
              "secondary-fixed": "#e1e3e4",
              "on-background": "#191c1d",
              "surface-container-highest": "#e1e3e4",
              "secondary-container": "#e1e3e4",
              "on-surface": "#191c1d",
              "inverse-surface": "#2e3132",
              "surface-tint": "#595c7b",
              "tertiary-fixed": "#ffdad8",
              "surface-dim": "#d9dadb",
              "on-primary-container": "#7f81a2",
              "tertiary-container": "#410007",
              "error": "#ba1a1a",
              "surface-bright": "#f8f9fa",
              "outline": "#77767e",
              "on-secondary-container": "#626566",
              "on-error": "#ffffff",
              "surface": "#f8f9fa",
              "on-primary-fixed-variant": "#424562",
              "on-tertiary-fixed-variant": "#92001c",
              "surface-container": "#edeeef",
              "on-secondary": "#ffffff",
              "error-container": "#ffdad6",
              "on-secondary-fixed-variant": "#454748",
              "inverse-primary": "#c2c4e8",
              "inverse-on-surface": "#f0f1f2",
              "primary-fixed": "#dfe0ff",
              "on-primary-fixed": "#161934",
              "tertiary": "#000000",
              "surface-container-low": "#f3f4f5",
              "primary-container": "#161934",
              "background": "#f8f9fa",
              "primary": "#000000",
              "surface-container-high": "#e7e8e9"
          },
          "borderRadius": {
              "DEFAULT": "1rem",
              "lg": "2rem",
              "xl": "3rem",
              "full": "9999px"
          },
          "fontFamily": {
              "headline": ["Manrope"],
              "body": ["Inter"],
              "label": ["Inter"],
              "manrope": ["Manrope"]
          }
      },
  },
  plugins: [],
}
